#!/bin/bash

################################################################################
# Auto Push Diagnostics to GitHub
# Run this after collecting diagnostics to automatically commit and push
################################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}Auto Push Diagnostics${NC}"
echo -e "${BLUE}================================${NC}"
echo ""

################################################################################
# Check if diagnostics exist
################################################################################
if [ ! -d "diagnostics/output" ] || [ -z "$(ls -A diagnostics/output 2>/dev/null | grep -v '.gitkeep')" ]; then
    echo -e "${RED}❌ No diagnostics found!${NC}"
    echo ""
    echo "Run diagnostics first:"
    echo "  ./quick_start.sh"
    echo "  OR"
    echo "  ./collect_diagnostics.sh"
    echo ""
    exit 1
fi

################################################################################
# Show what will be added
################################################################################
echo -e "${YELLOW}Files to be added:${NC}"
echo ""

# Find diagnostic runs
DIAGNOSTIC_RUNS=$(find diagnostics/output -type d -name "run_*" 2>/dev/null || true)
JSON_SPILLS=$(find diagnostics/output -type f -name "json_spill_analysis_*.txt" 2>/dev/null || true)

if [ -n "$DIAGNOSTIC_RUNS" ]; then
    echo "📊 Diagnostic runs:"
    echo "$DIAGNOSTIC_RUNS" | while read -r dir; do
        RUN_NAME=$(basename "$dir")
        FILE_COUNT=$(find "$dir" -type f | wc -l | tr -d ' ')
        SIZE=$(du -sh "$dir" 2>/dev/null | cut -f1)
        echo "  ✓ $RUN_NAME ($FILE_COUNT files, $SIZE)"
    done
    echo ""
fi

if [ -n "$JSON_SPILLS" ]; then
    echo "🔍 JSON spill analyses:"
    echo "$JSON_SPILLS" | while read -r file; do
        FILE_NAME=$(basename "$file")
        SIZE=$(du -h "$file" 2>/dev/null | cut -f1)
        echo "  ✓ $FILE_NAME ($SIZE)"
    done
    echo ""
fi

################################################################################
# Confirmation
################################################################################
echo -e "${YELLOW}This will:${NC}"
echo "  1. Add diagnostic files (even though gitignored)"
echo "  2. Commit with auto-generated message"
echo "  3. Push to GitHub main branch"
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Cancelled.${NC}"
    exit 0
fi

################################################################################
# Add files
################################################################################
echo ""
echo -e "${YELLOW}[1/3] Adding diagnostic files...${NC}"

# Add all diagnostic runs (force add despite .gitignore)
git add -f diagnostics/output/run_*/ 2>/dev/null || true

# Add JSON spill analyses
git add -f diagnostics/output/json_spill_analysis_*.txt 2>/dev/null || true

# Add analysis files if any exist
git add diagnostics/analysis/*.md 2>/dev/null || true

echo -e "${GREEN}✅ Files added${NC}"

################################################################################
# Show git status
################################################################################
echo ""
echo -e "${BLUE}Git status:${NC}"
git status --short
echo ""

################################################################################
# Check if there's anything to commit
################################################################################
if git diff --cached --quiet; then
    echo -e "${YELLOW}⚠️  No changes to commit (files might already be pushed)${NC}"
    echo ""
    echo "Current status:"
    git status
    exit 0
fi

################################################################################
# Commit
################################################################################
echo -e "${YELLOW}[2/3] Creating commit...${NC}"

# Auto-generate commit message with timestamp
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
RUN_COUNT=$(find diagnostics/output -type d -name "run_*" 2>/dev/null | wc -l | tr -d ' ')

COMMIT_MSG="Add diagnostics run - $TIMESTAMP

Diagnostic runs: $RUN_COUNT
Generated by: auto_push.sh"

git commit -m "$COMMIT_MSG"

echo -e "${GREEN}✅ Committed${NC}"
echo ""

################################################################################
# Push
################################################################################
echo -e "${YELLOW}[3/3] Pushing to GitHub...${NC}"
echo ""

if git push origin main; then
    echo ""
    echo -e "${GREEN}✅ Successfully pushed to GitHub!${NC}"
    echo ""
    echo -e "${BLUE}Repository: https://github.com/tomltran7/fixing-claude-local${NC}"
    echo ""
    echo -e "${GREEN}Next steps:${NC}"
    echo "  1. Notify Devin: 'Diagnostics uploaded at $TIMESTAMP'"
    echo "  2. Wait for analysis and fixes"
    echo "  3. Pull updates: git pull"
    echo "  4. Review analysis: cat diagnostics/analysis/findings_*.md"
    echo "  5. Run fixes: ./fixes/fix_*.sh"
    echo ""
else
    echo ""
    echo -e "${RED}❌ Push failed${NC}"
    echo ""
    echo "Common issues:"
    echo "  - Check internet connection"
    echo "  - Verify GitHub credentials"
    echo "  - Try: git pull --rebase && git push"
    echo ""
    exit 1
fi
